<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="EnemiesModel\Types\Assets\goblin.png" />
    <None Remove="EnemiesModel\Types\Assets\mage.png" />
    <None Remove="EnemiesModel\Types\Assets\werwolf.png" />
    <None Remove="Maps\Assets\Map1.png" />
    <None Remove="Projectils\Types\Assets\IceBall.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="EnemiesModel\Types\Assets\goblin.png" />
    <Resource Include="EnemiesModel\Types\Assets\mage.png" />
    <Resource Include="EnemiesModel\Types\Assets\werwolf.png" />
    <Resource Include="Maps\Assets\Map1.png" />
    <Resource Include="Projectils\Types\Assets\IceBall.png" />
  </ItemGroup>

</Project>
